# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 21:17
from __future__ import unicode_literals

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326),
        ),
    ]
