# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 12:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('snapshot', models.ImageField(blank=True, upload_to='project_snips')),
                ('platform', models.URLField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
                ('details', models.CharField(max_length=128)),
                ('fa_icon', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='squad_pics')),
                ('profile', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Squad',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your name.', max_length=128)),
                ('email', models.EmailField(help_text='Please enter your email address.', max_length=254, unique=True)),
                ('organization', models.CharField(blank=True, help_text='Please enter name of institution.', max_length=128)),
                ('phone', models.CharField(blank=True, help_text='Please enter phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message="Enter phone number in the format:'+2547698111...'", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField(help_text='Please enter a message.', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(unique=True)),
                ('interest', models.ManyToManyField(blank=True, help_text='Please select service of interest', to='aceapp.Service')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aceapp.Service'),
        ),
    ]
