# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='project_snips'),
        ),
    ]
