# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 17:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceapp', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='interest',
            field=models.ManyToManyField(blank=True, help_text='Please select service of interest.', to='aceapp.Service'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='message',
            field=models.TextField(help_text='Please describe your project requirements.', max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, help_text='please enter phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message="Enter phone number in the format:'+2547698.....'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
